// Generated by packages/live/scripts/generate-capability-types.mjs. Do not edit.
// Source schema SHA-256: 58d927afe6df0964e58c33dfb9434bec0206eee0ac452c18369433c4f143dac3

export type Identity = string;
export type DatabaseName = string;

/**
 * Strict decoded JWE protected-header and claims contract. Compact serialization and cryptographic requirements are recorded in x-jweCompact.
 */
export interface NeonLiveQueryCapabilityV1 {
  protected: ProtectedHeader;
  claims: Claims;
}
export interface ProtectedHeader {
  alg: "dir";
  enc: "A256GCM";
  kid: string;
  v: 1;
}
export interface Claims {
  v: 1;
  aud: "neon-live-proxy";
  iss: Identity;
  database: DatabaseName;
  query_fingerprint: string;
  sql: string;
  /**
   * @maxItems 256
   */
  parameters: Parameter[];
  iat: number;
  exp: number;
}
export interface Parameter {
  /**
   * Optional PostgreSQL type hint. Omission or zero requests SQL-context inference.
   */
  type_oid?: number;
  value: null | string;
}
