// This file is auto-generated by scripts/generate-raw.mjs. Do not edit.
// It wraps every generated operation from ./sdk.gen.ts with the ergonomic result contract.

import { wrapRaw } from "../neon/raw-wrap.js";
import {
	acceptProjectTransferRequest as _acceptProjectTransferRequest,
	addBranchNeonAuthOauthProvider as _addBranchNeonAuthOauthProvider,
	addBranchNeonAuthTrustedDomain as _addBranchNeonAuthTrustedDomain,
	addNeonAuthDomainToRedirectUriWhitelist as _addNeonAuthDomainToRedirectUriWhitelist,
	addNeonAuthOauthProvider as _addNeonAuthOauthProvider,
	addProjectJwks as _addProjectJwks,
	assignOrganizationVpcEndpoint as _assignOrganizationVpcEndpoint,
	assignProjectVpcEndpoint as _assignProjectVpcEndpoint,
	countProjectBranches as _countProjectBranches,
	createApiKey as _createApiKey,
	createBranchNeonAuthNewUser as _createBranchNeonAuthNewUser,
	createCredential as _createCredential,
	createNeonAuth as _createNeonAuth,
	createNeonAuthIntegration as _createNeonAuthIntegration,
	createNeonAuthNewUser as _createNeonAuthNewUser,
	createNeonAuthProviderSdkKeys as _createNeonAuthProviderSdkKeys,
	createOrganizationInvitations as _createOrganizationInvitations,
	createOrgApiKey as _createOrgApiKey,
	createProject as _createProject,
	createProjectBranch as _createProjectBranch,
	createProjectBranchAnonymized as _createProjectBranchAnonymized,
	createProjectBranchBucket as _createProjectBranchBucket,
	createProjectBranchDataApi as _createProjectBranchDataApi,
	createProjectBranchDatabase as _createProjectBranchDatabase,
	createProjectBranchFunctionDeployment as _createProjectBranchFunctionDeployment,
	createProjectBranchRole as _createProjectBranchRole,
	createProjectEndpoint as _createProjectEndpoint,
	createProjectTransferRequest as _createProjectTransferRequest,
	createSnapshot as _createSnapshot,
	deleteBranchNeonAuthOauthProvider as _deleteBranchNeonAuthOauthProvider,
	deleteBranchNeonAuthTrustedDomain as _deleteBranchNeonAuthTrustedDomain,
	deleteBranchNeonAuthUser as _deleteBranchNeonAuthUser,
	deleteNeonAuthDomainFromRedirectUriWhitelist as _deleteNeonAuthDomainFromRedirectUriWhitelist,
	deleteNeonAuthIntegration as _deleteNeonAuthIntegration,
	deleteNeonAuthOauthProvider as _deleteNeonAuthOauthProvider,
	deleteNeonAuthUser as _deleteNeonAuthUser,
	deleteOrganizationSpendingLimit as _deleteOrganizationSpendingLimit,
	deleteOrganizationVpcEndpoint as _deleteOrganizationVpcEndpoint,
	deleteProject as _deleteProject,
	deleteProjectBranch as _deleteProjectBranch,
	deleteProjectBranchBucket as _deleteProjectBranchBucket,
	deleteProjectBranchBucketObject as _deleteProjectBranchBucketObject,
	deleteProjectBranchBucketObjectsByPrefix as _deleteProjectBranchBucketObjectsByPrefix,
	deleteProjectBranchDataApi as _deleteProjectBranchDataApi,
	deleteProjectBranchDatabase as _deleteProjectBranchDatabase,
	deleteProjectBranchFunction as _deleteProjectBranchFunction,
	deleteProjectBranchRole as _deleteProjectBranchRole,
	deleteProjectEndpoint as _deleteProjectEndpoint,
	deleteProjectJwks as _deleteProjectJwks,
	deleteProjectVpcEndpoint as _deleteProjectVpcEndpoint,
	deleteSnapshot as _deleteSnapshot,
	disableNeonAuth as _disableNeonAuth,
	finalizeRestoreBranch as _finalizeRestoreBranch,
	getActiveRegions as _getActiveRegions,
	getAnonymizedBranchStatus as _getAnonymizedBranchStatus,
	getAuthDetails as _getAuthDetails,
	getAvailablePreloadLibraries as _getAvailablePreloadLibraries,
	getConnectionUri as _getConnectionUri,
	getConsumptionHistoryPerBranchV2 as _getConsumptionHistoryPerBranchV2,
	getConsumptionHistoryPerProject as _getConsumptionHistoryPerProject,
	getConsumptionHistoryPerProjectV2 as _getConsumptionHistoryPerProjectV2,
	getCurrentUserInfo as _getCurrentUserInfo,
	getCurrentUserOrganizations as _getCurrentUserOrganizations,
	getMaskingRules as _getMaskingRules,
	getNeonAuth as _getNeonAuth,
	getNeonAuthAllowLocalhost as _getNeonAuthAllowLocalhost,
	getNeonAuthEmailAndPasswordConfig as _getNeonAuthEmailAndPasswordConfig,
	getNeonAuthEmailProvider as _getNeonAuthEmailProvider,
	getNeonAuthEmailServer as _getNeonAuthEmailServer,
	getNeonAuthPhoneNumberPlugin as _getNeonAuthPhoneNumberPlugin,
	getNeonAuthPluginConfigs as _getNeonAuthPluginConfigs,
	getNeonAuthWebhookConfig as _getNeonAuthWebhookConfig,
	getOrganization as _getOrganization,
	getOrganizationInvitations as _getOrganizationInvitations,
	getOrganizationMember as _getOrganizationMember,
	getOrganizationMembers as _getOrganizationMembers,
	getOrganizationSpendingLimit as _getOrganizationSpendingLimit,
	getOrganizationVpcEndpointDetails as _getOrganizationVpcEndpointDetails,
	getProject as _getProject,
	getProjectAdvisorSecurityIssues as _getProjectAdvisorSecurityIssues,
	getProjectBranch as _getProjectBranch,
	getProjectBranchAiGateway as _getProjectBranchAiGateway,
	getProjectBranchBucketObject as _getProjectBranchBucketObject,
	getProjectBranchDataApi as _getProjectBranchDataApi,
	getProjectBranchDatabase as _getProjectBranchDatabase,
	getProjectBranchFunction as _getProjectBranchFunction,
	getProjectBranchRole as _getProjectBranchRole,
	getProjectBranchRolePassword as _getProjectBranchRolePassword,
	getProjectBranchSchema as _getProjectBranchSchema,
	getProjectBranchSchemaComparison as _getProjectBranchSchemaComparison,
	getProjectBranchStorage as _getProjectBranchStorage,
	getProjectEndpoint as _getProjectEndpoint,
	getProjectJwks as _getProjectJwks,
	getProjectOperation as _getProjectOperation,
	getSnapshotSchedule as _getSnapshotSchedule,
	grantPermissionToProject as _grantPermissionToProject,
	listApiKeys as _listApiKeys,
	listBranchNeonAuthOauthProviders as _listBranchNeonAuthOauthProviders,
	listBranchNeonAuthTrustedDomains as _listBranchNeonAuthTrustedDomains,
	listCredentials as _listCredentials,
	listNeonAuthIntegrations as _listNeonAuthIntegrations,
	listNeonAuthOauthProviders as _listNeonAuthOauthProviders,
	listNeonAuthRedirectUriWhitelistDomains as _listNeonAuthRedirectUriWhitelistDomains,
	listOrganizationVpcEndpoints as _listOrganizationVpcEndpoints,
	listOrganizationVpcEndpointsAllRegions as _listOrganizationVpcEndpointsAllRegions,
	listOrgApiKeys as _listOrgApiKeys,
	listProjectBranchBucketObjects as _listProjectBranchBucketObjects,
	listProjectBranchBuckets as _listProjectBranchBuckets,
	listProjectBranchDatabases as _listProjectBranchDatabases,
	listProjectBranchEndpoints as _listProjectBranchEndpoints,
	listProjectBranches as _listProjectBranches,
	listProjectBranchFunctions as _listProjectBranchFunctions,
	listProjectBranchRoles as _listProjectBranchRoles,
	listProjectEndpoints as _listProjectEndpoints,
	listProjectOperations as _listProjectOperations,
	listProjectPermissions as _listProjectPermissions,
	listProjects as _listProjects,
	listProjectVpcEndpoints as _listProjectVpcEndpoints,
	listSharedProjects as _listSharedProjects,
	listSnapshots as _listSnapshots,
	presignProjectBranchBucketObject as _presignProjectBranchBucketObject,
	recoverProject as _recoverProject,
	recoverProjectBranch as _recoverProjectBranch,
	removeOrganizationMember as _removeOrganizationMember,
	resetProjectBranchRolePassword as _resetProjectBranchRolePassword,
	restartProjectEndpoint as _restartProjectEndpoint,
	restoreProjectBranch as _restoreProjectBranch,
	restoreSnapshot as _restoreSnapshot,
	revokeApiKey as _revokeApiKey,
	revokeCredential as _revokeCredential,
	revokeOrgApiKey as _revokeOrgApiKey,
	revokePermissionFromProject as _revokePermissionFromProject,
	sendNeonAuthTestEmail as _sendNeonAuthTestEmail,
	setDefaultProjectBranch as _setDefaultProjectBranch,
	setOrganizationSpendingLimit as _setOrganizationSpendingLimit,
	setSnapshotSchedule as _setSnapshotSchedule,
	startAnonymization as _startAnonymization,
	startProjectEndpoint as _startProjectEndpoint,
	suspendProjectEndpoint as _suspendProjectEndpoint,
	transferNeonAuthProviderProject as _transferNeonAuthProviderProject,
	transferProjectsFromOrgToOrg as _transferProjectsFromOrgToOrg,
	transferProjectsFromUserToOrg as _transferProjectsFromUserToOrg,
	updateBranchNeonAuthOauthProvider as _updateBranchNeonAuthOauthProvider,
	updateMaskingRules as _updateMaskingRules,
	updateNeonAuthAllowLocalhost as _updateNeonAuthAllowLocalhost,
	updateNeonAuthConfig as _updateNeonAuthConfig,
	updateNeonAuthEmailAndPasswordConfig as _updateNeonAuthEmailAndPasswordConfig,
	updateNeonAuthEmailProvider as _updateNeonAuthEmailProvider,
	updateNeonAuthEmailServer as _updateNeonAuthEmailServer,
	updateNeonAuthMagicLinkPlugin as _updateNeonAuthMagicLinkPlugin,
	updateNeonAuthOauthProvider as _updateNeonAuthOauthProvider,
	updateNeonAuthOrganizationPlugin as _updateNeonAuthOrganizationPlugin,
	updateNeonAuthPhoneNumberPlugin as _updateNeonAuthPhoneNumberPlugin,
	updateNeonAuthUserRole as _updateNeonAuthUserRole,
	updateNeonAuthWebhookConfig as _updateNeonAuthWebhookConfig,
	updateOrganizationMember as _updateOrganizationMember,
	updateProject as _updateProject,
	updateProjectBranch as _updateProjectBranch,
	updateProjectBranchDataApi as _updateProjectBranchDataApi,
	updateProjectBranchDatabase as _updateProjectBranchDatabase,
	updateProjectBranchFunction as _updateProjectBranchFunction,
	updateProjectEndpoint as _updateProjectEndpoint,
	updateSnapshot as _updateSnapshot,
} from "./sdk.gen.js";

export const acceptProjectTransferRequest = wrapRaw(_acceptProjectTransferRequest);
export const addBranchNeonAuthOauthProvider = wrapRaw(_addBranchNeonAuthOauthProvider);
export const addBranchNeonAuthTrustedDomain = wrapRaw(_addBranchNeonAuthTrustedDomain);
export const addNeonAuthDomainToRedirectUriWhitelist = wrapRaw(_addNeonAuthDomainToRedirectUriWhitelist);
export const addNeonAuthOauthProvider = wrapRaw(_addNeonAuthOauthProvider);
export const addProjectJwks = wrapRaw(_addProjectJwks);
export const assignOrganizationVpcEndpoint = wrapRaw(_assignOrganizationVpcEndpoint);
export const assignProjectVpcEndpoint = wrapRaw(_assignProjectVpcEndpoint);
export const countProjectBranches = wrapRaw(_countProjectBranches);
export const createApiKey = wrapRaw(_createApiKey);
export const createBranchNeonAuthNewUser = wrapRaw(_createBranchNeonAuthNewUser);
export const createCredential = wrapRaw(_createCredential);
export const createNeonAuth = wrapRaw(_createNeonAuth);
export const createNeonAuthIntegration = wrapRaw(_createNeonAuthIntegration);
export const createNeonAuthNewUser = wrapRaw(_createNeonAuthNewUser);
export const createNeonAuthProviderSdkKeys = wrapRaw(_createNeonAuthProviderSdkKeys);
export const createOrganizationInvitations = wrapRaw(_createOrganizationInvitations);
export const createOrgApiKey = wrapRaw(_createOrgApiKey);
export const createProject = wrapRaw(_createProject);
export const createProjectBranch = wrapRaw(_createProjectBranch);
export const createProjectBranchAnonymized = wrapRaw(_createProjectBranchAnonymized);
export const createProjectBranchBucket = wrapRaw(_createProjectBranchBucket);
export const createProjectBranchDataApi = wrapRaw(_createProjectBranchDataApi);
export const createProjectBranchDatabase = wrapRaw(_createProjectBranchDatabase);
export const createProjectBranchFunctionDeployment = wrapRaw(_createProjectBranchFunctionDeployment);
export const createProjectBranchRole = wrapRaw(_createProjectBranchRole);
export const createProjectEndpoint = wrapRaw(_createProjectEndpoint);
export const createProjectTransferRequest = wrapRaw(_createProjectTransferRequest);
export const createSnapshot = wrapRaw(_createSnapshot);
export const deleteBranchNeonAuthOauthProvider = wrapRaw(_deleteBranchNeonAuthOauthProvider);
export const deleteBranchNeonAuthTrustedDomain = wrapRaw(_deleteBranchNeonAuthTrustedDomain);
export const deleteBranchNeonAuthUser = wrapRaw(_deleteBranchNeonAuthUser);
export const deleteNeonAuthDomainFromRedirectUriWhitelist = wrapRaw(_deleteNeonAuthDomainFromRedirectUriWhitelist);
export const deleteNeonAuthIntegration = wrapRaw(_deleteNeonAuthIntegration);
export const deleteNeonAuthOauthProvider = wrapRaw(_deleteNeonAuthOauthProvider);
export const deleteNeonAuthUser = wrapRaw(_deleteNeonAuthUser);
export const deleteOrganizationSpendingLimit = wrapRaw(_deleteOrganizationSpendingLimit);
export const deleteOrganizationVpcEndpoint = wrapRaw(_deleteOrganizationVpcEndpoint);
export const deleteProject = wrapRaw(_deleteProject);
export const deleteProjectBranch = wrapRaw(_deleteProjectBranch);
export const deleteProjectBranchBucket = wrapRaw(_deleteProjectBranchBucket);
export const deleteProjectBranchBucketObject = wrapRaw(_deleteProjectBranchBucketObject);
export const deleteProjectBranchBucketObjectsByPrefix = wrapRaw(_deleteProjectBranchBucketObjectsByPrefix);
export const deleteProjectBranchDataApi = wrapRaw(_deleteProjectBranchDataApi);
export const deleteProjectBranchDatabase = wrapRaw(_deleteProjectBranchDatabase);
export const deleteProjectBranchFunction = wrapRaw(_deleteProjectBranchFunction);
export const deleteProjectBranchRole = wrapRaw(_deleteProjectBranchRole);
export const deleteProjectEndpoint = wrapRaw(_deleteProjectEndpoint);
export const deleteProjectJwks = wrapRaw(_deleteProjectJwks);
export const deleteProjectVpcEndpoint = wrapRaw(_deleteProjectVpcEndpoint);
export const deleteSnapshot = wrapRaw(_deleteSnapshot);
export const disableNeonAuth = wrapRaw(_disableNeonAuth);
export const finalizeRestoreBranch = wrapRaw(_finalizeRestoreBranch);
export const getActiveRegions = wrapRaw(_getActiveRegions);
export const getAnonymizedBranchStatus = wrapRaw(_getAnonymizedBranchStatus);
export const getAuthDetails = wrapRaw(_getAuthDetails);
export const getAvailablePreloadLibraries = wrapRaw(_getAvailablePreloadLibraries);
export const getConnectionUri = wrapRaw(_getConnectionUri);
export const getConsumptionHistoryPerBranchV2 = wrapRaw(_getConsumptionHistoryPerBranchV2);
export const getConsumptionHistoryPerProject = wrapRaw(_getConsumptionHistoryPerProject);
export const getConsumptionHistoryPerProjectV2 = wrapRaw(_getConsumptionHistoryPerProjectV2);
export const getCurrentUserInfo = wrapRaw(_getCurrentUserInfo);
export const getCurrentUserOrganizations = wrapRaw(_getCurrentUserOrganizations);
export const getMaskingRules = wrapRaw(_getMaskingRules);
export const getNeonAuth = wrapRaw(_getNeonAuth);
export const getNeonAuthAllowLocalhost = wrapRaw(_getNeonAuthAllowLocalhost);
export const getNeonAuthEmailAndPasswordConfig = wrapRaw(_getNeonAuthEmailAndPasswordConfig);
export const getNeonAuthEmailProvider = wrapRaw(_getNeonAuthEmailProvider);
export const getNeonAuthEmailServer = wrapRaw(_getNeonAuthEmailServer);
export const getNeonAuthPhoneNumberPlugin = wrapRaw(_getNeonAuthPhoneNumberPlugin);
export const getNeonAuthPluginConfigs = wrapRaw(_getNeonAuthPluginConfigs);
export const getNeonAuthWebhookConfig = wrapRaw(_getNeonAuthWebhookConfig);
export const getOrganization = wrapRaw(_getOrganization);
export const getOrganizationInvitations = wrapRaw(_getOrganizationInvitations);
export const getOrganizationMember = wrapRaw(_getOrganizationMember);
export const getOrganizationMembers = wrapRaw(_getOrganizationMembers);
export const getOrganizationSpendingLimit = wrapRaw(_getOrganizationSpendingLimit);
export const getOrganizationVpcEndpointDetails = wrapRaw(_getOrganizationVpcEndpointDetails);
export const getProject = wrapRaw(_getProject);
export const getProjectAdvisorSecurityIssues = wrapRaw(_getProjectAdvisorSecurityIssues);
export const getProjectBranch = wrapRaw(_getProjectBranch);
export const getProjectBranchAiGateway = wrapRaw(_getProjectBranchAiGateway);
export const getProjectBranchBucketObject = wrapRaw(_getProjectBranchBucketObject);
export const getProjectBranchDataApi = wrapRaw(_getProjectBranchDataApi);
export const getProjectBranchDatabase = wrapRaw(_getProjectBranchDatabase);
export const getProjectBranchFunction = wrapRaw(_getProjectBranchFunction);
export const getProjectBranchRole = wrapRaw(_getProjectBranchRole);
export const getProjectBranchRolePassword = wrapRaw(_getProjectBranchRolePassword);
export const getProjectBranchSchema = wrapRaw(_getProjectBranchSchema);
export const getProjectBranchSchemaComparison = wrapRaw(_getProjectBranchSchemaComparison);
export const getProjectBranchStorage = wrapRaw(_getProjectBranchStorage);
export const getProjectEndpoint = wrapRaw(_getProjectEndpoint);
export const getProjectJwks = wrapRaw(_getProjectJwks);
export const getProjectOperation = wrapRaw(_getProjectOperation);
export const getSnapshotSchedule = wrapRaw(_getSnapshotSchedule);
export const grantPermissionToProject = wrapRaw(_grantPermissionToProject);
export const listApiKeys = wrapRaw(_listApiKeys);
export const listBranchNeonAuthOauthProviders = wrapRaw(_listBranchNeonAuthOauthProviders);
export const listBranchNeonAuthTrustedDomains = wrapRaw(_listBranchNeonAuthTrustedDomains);
export const listCredentials = wrapRaw(_listCredentials);
export const listNeonAuthIntegrations = wrapRaw(_listNeonAuthIntegrations);
export const listNeonAuthOauthProviders = wrapRaw(_listNeonAuthOauthProviders);
export const listNeonAuthRedirectUriWhitelistDomains = wrapRaw(_listNeonAuthRedirectUriWhitelistDomains);
export const listOrganizationVpcEndpoints = wrapRaw(_listOrganizationVpcEndpoints);
export const listOrganizationVpcEndpointsAllRegions = wrapRaw(_listOrganizationVpcEndpointsAllRegions);
export const listOrgApiKeys = wrapRaw(_listOrgApiKeys);
export const listProjectBranchBucketObjects = wrapRaw(_listProjectBranchBucketObjects);
export const listProjectBranchBuckets = wrapRaw(_listProjectBranchBuckets);
export const listProjectBranchDatabases = wrapRaw(_listProjectBranchDatabases);
export const listProjectBranchEndpoints = wrapRaw(_listProjectBranchEndpoints);
export const listProjectBranches = wrapRaw(_listProjectBranches);
export const listProjectBranchFunctions = wrapRaw(_listProjectBranchFunctions);
export const listProjectBranchRoles = wrapRaw(_listProjectBranchRoles);
export const listProjectEndpoints = wrapRaw(_listProjectEndpoints);
export const listProjectOperations = wrapRaw(_listProjectOperations);
export const listProjectPermissions = wrapRaw(_listProjectPermissions);
export const listProjects = wrapRaw(_listProjects);
export const listProjectVpcEndpoints = wrapRaw(_listProjectVpcEndpoints);
export const listSharedProjects = wrapRaw(_listSharedProjects);
export const listSnapshots = wrapRaw(_listSnapshots);
export const presignProjectBranchBucketObject = wrapRaw(_presignProjectBranchBucketObject);
export const recoverProject = wrapRaw(_recoverProject);
export const recoverProjectBranch = wrapRaw(_recoverProjectBranch);
export const removeOrganizationMember = wrapRaw(_removeOrganizationMember);
export const resetProjectBranchRolePassword = wrapRaw(_resetProjectBranchRolePassword);
export const restartProjectEndpoint = wrapRaw(_restartProjectEndpoint);
export const restoreProjectBranch = wrapRaw(_restoreProjectBranch);
export const restoreSnapshot = wrapRaw(_restoreSnapshot);
export const revokeApiKey = wrapRaw(_revokeApiKey);
export const revokeCredential = wrapRaw(_revokeCredential);
export const revokeOrgApiKey = wrapRaw(_revokeOrgApiKey);
export const revokePermissionFromProject = wrapRaw(_revokePermissionFromProject);
export const sendNeonAuthTestEmail = wrapRaw(_sendNeonAuthTestEmail);
export const setDefaultProjectBranch = wrapRaw(_setDefaultProjectBranch);
export const setOrganizationSpendingLimit = wrapRaw(_setOrganizationSpendingLimit);
export const setSnapshotSchedule = wrapRaw(_setSnapshotSchedule);
export const startAnonymization = wrapRaw(_startAnonymization);
export const startProjectEndpoint = wrapRaw(_startProjectEndpoint);
export const suspendProjectEndpoint = wrapRaw(_suspendProjectEndpoint);
export const transferNeonAuthProviderProject = wrapRaw(_transferNeonAuthProviderProject);
export const transferProjectsFromOrgToOrg = wrapRaw(_transferProjectsFromOrgToOrg);
export const transferProjectsFromUserToOrg = wrapRaw(_transferProjectsFromUserToOrg);
export const updateBranchNeonAuthOauthProvider = wrapRaw(_updateBranchNeonAuthOauthProvider);
export const updateMaskingRules = wrapRaw(_updateMaskingRules);
export const updateNeonAuthAllowLocalhost = wrapRaw(_updateNeonAuthAllowLocalhost);
export const updateNeonAuthConfig = wrapRaw(_updateNeonAuthConfig);
export const updateNeonAuthEmailAndPasswordConfig = wrapRaw(_updateNeonAuthEmailAndPasswordConfig);
export const updateNeonAuthEmailProvider = wrapRaw(_updateNeonAuthEmailProvider);
export const updateNeonAuthEmailServer = wrapRaw(_updateNeonAuthEmailServer);
export const updateNeonAuthMagicLinkPlugin = wrapRaw(_updateNeonAuthMagicLinkPlugin);
export const updateNeonAuthOauthProvider = wrapRaw(_updateNeonAuthOauthProvider);
export const updateNeonAuthOrganizationPlugin = wrapRaw(_updateNeonAuthOrganizationPlugin);
export const updateNeonAuthPhoneNumberPlugin = wrapRaw(_updateNeonAuthPhoneNumberPlugin);
export const updateNeonAuthUserRole = wrapRaw(_updateNeonAuthUserRole);
export const updateNeonAuthWebhookConfig = wrapRaw(_updateNeonAuthWebhookConfig);
export const updateOrganizationMember = wrapRaw(_updateOrganizationMember);
export const updateProject = wrapRaw(_updateProject);
export const updateProjectBranch = wrapRaw(_updateProjectBranch);
export const updateProjectBranchDataApi = wrapRaw(_updateProjectBranchDataApi);
export const updateProjectBranchDatabase = wrapRaw(_updateProjectBranchDatabase);
export const updateProjectBranchFunction = wrapRaw(_updateProjectBranchFunction);
export const updateProjectEndpoint = wrapRaw(_updateProjectEndpoint);
export const updateSnapshot = wrapRaw(_updateSnapshot);
