/**
 * Drift guard for the ergonomic layer.
 *
 * The raw layer is regenerated from the OpenAPI spec, so it auto-tracks new endpoints.
 * The ergonomic resource namespaces are hand-authored, so they can silently fall behind.
 * `coverage.test.ts` compares the generated operation set against {@link EXPECTED_OPERATIONS}
 * and fails CI when they differ — forcing a conscious decision on every spec change:
 * either wrap the new operation in a resource (and add it to {@link WRAPPED}) or accept
 * that it stays raw-only (and add it to the snapshot below).
 *
 * Workflow when the test fails after a `pnpm generate`:
 *   1. Review the `added` / `removed` operations the test reports.
 *   2. Wrap the ones worth ergonomic treatment (and list them in {@link WRAPPED}).
 *   3. Update {@link EXPECTED_OPERATIONS} to match the new generated set.
 */

/** Operations surfaced by the ergonomic `createNeonClient` namespaces. */
export const WRAPPED: ReadonlySet<string> = new Set([
	// projects
	"listProjects",
	"getProject",
	"createProject",
	"updateProject",
	"deleteProject",
	// projects: transfer
	"transferProjectsFromOrgToOrg",
	"transferProjectsFromUserToOrg",
	// projects: recover + permissions
	"recoverProject",
	"listProjectPermissions",
	"grantPermissionToProject",
	"revokePermissionFromProject",
	// projects: org member roles
	"listProjectMembers",
	"setProjectMemberRole",
	"removeProjectMemberRole",
	// branches
	"listProjectBranches",
	"getProjectBranch",
	"createProjectBranch",
	"updateProjectBranch",
	"deleteProjectBranch",
	"setDefaultProjectBranch",
	"finalizeRestoreBranch",
	// logs (branch-scoped)
	"queryProjectBranchLogs",
	"listProjectBranchLogFields",
	"listProjectBranchLogFieldValues",
	// neon auth (branch-scoped)
	"getNeonAuth",
	"createNeonAuth",
	"disableNeonAuth",
	"updateNeonAuthConfig",
	"listBranchNeonAuthOauthProviders",
	"addBranchNeonAuthOauthProvider",
	"updateBranchNeonAuthOauthProvider",
	"deleteBranchNeonAuthOauthProvider",
	"listBranchNeonAuthTrustedDomains",
	"addBranchNeonAuthTrustedDomain",
	"deleteBranchNeonAuthTrustedDomain",
	"createBranchNeonAuthNewUser",
	"deleteBranchNeonAuthUser",
	"updateNeonAuthUserRole",
	// storage
	"getProjectBranchStorage",
	"listProjectBranchBuckets",
	"createProjectBranchBucket",
	"deleteProjectBranchBucket",
	"listProjectBranchBucketObjects",
	"getProjectBranchBucketObject",
	"deleteProjectBranchBucketObject",
	"deleteProjectBranchBucketObjectsByPrefix",
	"presignProjectBranchBucketObject",
	// ai gateway
	"getProjectBranchAiGateway",
	// credentials
	"listCredentials",
	"createCredential",
	"revokeCredential",
	// functions
	"listProjectBranchFunctions",
	"getProjectBranchFunction",
	"updateProjectBranchFunction",
	"deleteProjectBranchFunction",
	"createProjectBranchFunctionDeployment",
	// operations
	"getProjectOperation",
	"listProjectOperations",
	// postgres: endpoints
	"listProjectEndpoints",
	"listProjectBranchEndpoints",
	"getProjectEndpoint",
	"createProjectEndpoint",
	"updateProjectEndpoint",
	"deleteProjectEndpoint",
	"startProjectEndpoint",
	"suspendProjectEndpoint",
	"restartProjectEndpoint",
	// postgres: databases
	"listProjectBranchDatabases",
	"getProjectBranchDatabase",
	"createProjectBranchDatabase",
	"updateProjectBranchDatabase",
	"deleteProjectBranchDatabase",
	// postgres: roles
	"listProjectBranchRoles",
	"getProjectBranchRole",
	"createProjectBranchRole",
	"deleteProjectBranchRole",
	"getProjectBranchRolePassword",
	"resetProjectBranchRolePassword",
	// postgres: connection string + data api
	"getConnectionUri",
	"getProjectBranchDataApi",
	"createProjectBranchDataApi",
	"updateProjectBranchDataApi",
	"deleteProjectBranchDataApi",
	// snapshots
	"listSnapshots",
	"createSnapshot",
	"updateSnapshot",
	"deleteSnapshot",
	"restoreSnapshot",
	"getSnapshotSchedule",
	"setSnapshotSchedule",
	// consumption
	"getConsumptionHistoryPerProject",
	"getConsumptionHistoryPerProjectV2",
	"getConsumptionHistoryPerBranchV2",
	// account
	"getCurrentUserInfo",
	"getCurrentUserOrganizations",
	"getActiveRegions",
	"listApiKeys",
	"createApiKey",
	"revokeApiKey",
]);

/**
 * Committed snapshot of every operation the generated client exposes. Update this
 * deliberately whenever the spec (and thus the generated client) changes.
 */
export const EXPECTED_OPERATIONS: ReadonlySet<string> = new Set([
	"acceptProjectTransferRequest",
	"addBranchNeonAuthOauthProvider",
	"addBranchNeonAuthTrustedDomain",
	"addNeonAuthDomainToRedirectUriWhitelist",
	"addNeonAuthOauthProvider",
	"addProjectJwks",
	"assignOrganizationVpcEndpoint",
	"assignProjectVpcEndpoint",
	"countProjectBranches",
	"createApiKey",
	"createBranchNeonAuthNewUser",
	"createCredential",
	"createNeonAuth",
	"createNeonAuthIntegration",
	"createNeonAuthNewUser",
	"createNeonAuthProviderSdkKeys",
	"createOrgApiKey",
	"createOrganizationInvitations",
	"createProject",
	"createProjectBranch",
	"createProjectBranchBucket",
	"createProjectBranchAnonymized",
	"createProjectBranchDataApi",
	"createProjectBranchDatabase",
	"createProjectBranchFunctionDeployment",
	"createProjectBranchRole",
	"createProjectEndpoint",
	"createProjectTransferRequest",
	"createSnapshot",
	"deleteBranchNeonAuthOauthProvider",
	"deleteBranchNeonAuthTrustedDomain",
	"deleteBranchNeonAuthUser",
	"deleteNeonAuthDomainFromRedirectUriWhitelist",
	"deleteNeonAuthIntegration",
	"deleteNeonAuthOauthProvider",
	"deleteNeonAuthUser",
	"deleteOrganizationSpendingLimit",
	"deleteOrganizationVpcEndpoint",
	"deleteProject",
	"deleteProjectBranch",
	"deleteProjectBranchBucket",
	"deleteProjectBranchBucketObject",
	"deleteProjectBranchBucketObjectsByPrefix",
	"deleteProjectBranchDataApi",
	"deleteProjectBranchDatabase",
	"deleteProjectBranchFunction",
	"deleteProjectBranchRole",
	"deleteProjectEndpoint",
	"deleteProjectJwks",
	"deleteProjectVpcEndpoint",
	"deleteSnapshot",
	"disableNeonAuth",
	"finalizeRestoreBranch",
	"getActiveRegions",
	"getAnonymizedBranchStatus",
	"getAuthDetails",
	"getAvailablePreloadLibraries",
	"getConnectionUri",
	"getConsumptionHistoryPerBranchV2",
	"getConsumptionHistoryPerProject",
	"getConsumptionHistoryPerProjectV2",
	"getCurrentUserInfo",
	"getCurrentUserOrganizations",
	"getMaskingRules",
	"getNeonAuth",
	"getNeonAuthAllowLocalhost",
	"getNeonAuthEmailAndPasswordConfig",
	"getNeonAuthEmailProvider",
	"getNeonAuthEmailServer",
	"getNeonAuthPhoneNumberPlugin",
	"getNeonAuthPluginConfigs",
	"getNeonAuthWebhookConfig",
	"getOrganization",
	"getOrganizationInvitations",
	"getOrganizationMember",
	"getOrganizationMembers",
	"getOrganizationSpendingLimit",
	"getOrganizationVpcEndpointDetails",
	"getProject",
	"getProjectAdvisorSecurityIssues",
	"getProjectBranch",
	"getProjectBranchAiGateway",
	"getProjectBranchBucketObject",
	"getProjectBranchDataApi",
	"getProjectBranchDatabase",
	"getProjectBranchFunction",
	"getProjectBranchRole",
	"getProjectBranchRolePassword",
	"getProjectBranchSchema",
	"getProjectBranchSchemaComparison",
	"getProjectBranchStorage",
	"getProjectEndpoint",
	"getProjectJwks",
	"getProjectOperation",
	"getSnapshotSchedule",
	"grantPermissionToProject",
	"listApiKeys",
	"listBranchNeonAuthOauthProviders",
	"listBranchNeonAuthTrustedDomains",
	"listCredentials",
	"listNeonAuthIntegrations",
	"listNeonAuthOauthProviders",
	"listNeonAuthRedirectUriWhitelistDomains",
	"listOrgApiKeys",
	"listOrganizationVpcEndpoints",
	"listOrganizationVpcEndpointsAllRegions",
	"listProjectBranchDatabases",
	"listProjectBranchBucketObjects",
	"listProjectBranchBuckets",
	"listProjectBranchEndpoints",
	"listProjectBranchRoles",
	"listProjectBranchFunctions",
	"listProjectBranchLogFields",
	"listProjectBranchLogFieldValues",
	"listProjectBranches",
	"listProjectEndpoints",
	"listProjectMembers",
	"listProjectOperations",
	"listProjectPermissions",
	"listProjectVpcEndpoints",
	"listProjects",
	"listSharedProjects",
	"listSnapshots",
	"presignProjectBranchBucketObject",
	"queryProjectBranchLogs",
	"recoverProject",
	"removeOrganizationMember",
	"removeProjectMemberRole",
	"resetProjectBranchRolePassword",
	"restartProjectEndpoint",
	"restoreProjectBranch",
	"restoreSnapshot",
	"revokeApiKey",
	"revokeCredential",
	"revokeOrgApiKey",
	"revokePermissionFromProject",
	"sendNeonAuthTestEmail",
	"setDefaultProjectBranch",
	"setOrganizationSpendingLimit",
	"setProjectMemberRole",
	"setSnapshotSchedule",
	"startAnonymization",
	"startProjectEndpoint",
	"suspendProjectEndpoint",
	"transferNeonAuthProviderProject",
	"transferProjectsFromOrgToOrg",
	"transferProjectsFromUserToOrg",
	"updateBranchNeonAuthOauthProvider",
	"updateMaskingRules",
	"updateNeonAuthAllowLocalhost",
	"updateNeonAuthConfig",
	"updateNeonAuthEmailAndPasswordConfig",
	"updateNeonAuthEmailProvider",
	"updateNeonAuthEmailServer",
	"updateNeonAuthMagicLinkPlugin",
	"updateNeonAuthOauthProvider",
	"updateNeonAuthOrganizationPlugin",
	"updateNeonAuthPhoneNumberPlugin",
	"updateNeonAuthUserRole",
	"updateNeonAuthWebhookConfig",
	"updateOrganizationMember",
	"updateProject",
	"updateProjectBranch",
	"updateProjectBranchDataApi",
	"updateProjectBranchDatabase",
	"updateProjectBranchFunction",
	"updateProjectEndpoint",
	"updateSnapshot",
]);
