// Generated by packages/realtime/scripts/generate-capability-types.mjs. Do not edit.
// Source schema SHA-256: e0d41546b8c8b24dd06af26d3bdab5cf582ef85728603ae805995d18e54cbbe1

export type Identity = string;
export type DatabaseName = string;

/**
 * Strict decoded JWE protected-header and claims contract. Compact serialization and cryptographic requirements are recorded in x-jweCompact.
 */
export interface NeonLiveQueryCapabilityV1 {
  protected: ProtectedHeader;
  claims: Claims;
}
export interface ProtectedHeader {
  alg: "dir";
  enc: "A256GCM";
  kid: string;
  v: 1;
}
export interface Claims {
  v: 1;
  aud: "realtime-proxy";
  iss: Identity;
  database: DatabaseName;
  query_fingerprint: string;
  sql: string;
  /**
   * @maxItems 256
   */
  parameters: Parameter[];
  iat: number;
  exp: number;
}
export interface Parameter {
  /**
   * Optional PostgreSQL type hint. Omission or zero requests SQL-context inference.
   */
  type_oid?: number;
  value: null | string;
}
