// Generated by packages/realtime/scripts/generate-capability-types.mjs. Do not edit.
// Source schema SHA-256: d1caa8e51098cf14ef8cc544a2e7dbd13f5bd2af8d93d664dd7efcb5c3c26c51

export type DatabaseName = string;

/**
 * Strict decoded JWE protected-header and claims contract. Compact serialization and cryptographic requirements are recorded in x-jweCompact.
 */
export interface RealtimeQueryCapabilityV1 {
  protected: ProtectedHeader;
  claims: Claims;
}
export interface ProtectedHeader {
  alg: "dir";
  enc: "A256GCM";
  v: 1;
}
export interface Claims {
  v: 1;
  aud: "realtime-proxy";
  database: DatabaseName;
  /**
   * Controls whether subscription errors use safe client-facing messages or include full database diagnostics.
   */
  error_details: "safe" | "full";
  query_fingerprint: string;
  sql: string;
  /**
   * @maxItems 256
   */
  parameters: Parameter[];
  iat: number;
  exp: number;
}
export interface Parameter {
  /**
   * Optional PostgreSQL type hint. Omission or zero requests SQL-context inference.
   */
  type_oid?: number;
  value: null | string;
}
