/** Stable PostgreSQL type OIDs used by the built-in Realtime parsers. */
export const pgTypeOids = Object.freeze({
	bool: 16,
	bytea: 17,
	char: 18,
	name: 19,
	int8: 20,
	int2: 21,
	int4: 23,
	text: 25,
	oid: 26,
	json: 114,
	xml: 142,
	point: 600,
	lseg: 601,
	path: 602,
	box: 603,
	polygon: 604,
	line: 628,
	cidr: 650,
	macaddr8: 774,
	money: 790,
	float4: 700,
	float8: 701,
	circle: 718,
	macaddr: 829,
	inet: 869,
	bpchar: 1042,
	varchar: 1043,
	date: 1082,
	time: 1083,
	timestamp: 1114,
	timestamptz: 1184,
	interval: 1186,
	timetz: 1266,
	bit: 1560,
	varbit: 1562,
	numeric: 1700,
	uuid: 2950,
	pgLsn: 3220,
	jsonb: 3802,
	cstring: 2275,

	jsonArray: 199,
	boolArray: 1000,
	byteaArray: 1001,
	charArray: 1002,
	nameArray: 1003,
	int2Array: 1005,
	int4Array: 1007,
	textArray: 1009,
	int8Array: 1016,
	pointArray: 1017,
	lsegArray: 1018,
	pathArray: 1019,
	boxArray: 1020,
	float4Array: 1021,
	float8Array: 1022,
	polygonArray: 1027,
	oidArray: 1028,
	macaddrArray: 1040,
	inetArray: 1041,
	bpcharArray: 1014,
	varcharArray: 1015,
	dateArray: 1182,
	timeArray: 1183,
	timestampArray: 1115,
	timestamptzArray: 1185,
	intervalArray: 1187,
	numericArray: 1231,
	timetzArray: 1270,
	bitArray: 1561,
	varbitArray: 1563,
	uuidArray: 2951,
	pgLsnArray: 3221,
	jsonbArray: 3807,
	lineArray: 629,
	cidrArray: 651,
	circleArray: 719,
	macaddr8Array: 775,
	moneyArray: 791,
	xmlArray: 143,
	cstringArray: 1263,
} as const);

export interface PostgresArrayType {
	readonly elementOid: number;
	readonly delimiter: "," | ";";
}

const arrayTypeEntries: ReadonlyArray<readonly [number, PostgresArrayType]> = [
	[pgTypeOids.jsonArray, { elementOid: pgTypeOids.json, delimiter: "," }],
	[pgTypeOids.boolArray, { elementOid: pgTypeOids.bool, delimiter: "," }],
	[pgTypeOids.byteaArray, { elementOid: pgTypeOids.bytea, delimiter: "," }],
	[pgTypeOids.charArray, { elementOid: pgTypeOids.char, delimiter: "," }],
	[pgTypeOids.nameArray, { elementOid: pgTypeOids.name, delimiter: "," }],
	[pgTypeOids.int2Array, { elementOid: pgTypeOids.int2, delimiter: "," }],
	[pgTypeOids.int4Array, { elementOid: pgTypeOids.int4, delimiter: "," }],
	[pgTypeOids.textArray, { elementOid: pgTypeOids.text, delimiter: "," }],
	[pgTypeOids.int8Array, { elementOid: pgTypeOids.int8, delimiter: "," }],
	[pgTypeOids.pointArray, { elementOid: pgTypeOids.point, delimiter: "," }],
	[pgTypeOids.lsegArray, { elementOid: pgTypeOids.lseg, delimiter: "," }],
	[pgTypeOids.pathArray, { elementOid: pgTypeOids.path, delimiter: "," }],
	[pgTypeOids.boxArray, { elementOid: pgTypeOids.box, delimiter: ";" }],
	[pgTypeOids.float4Array, { elementOid: pgTypeOids.float4, delimiter: "," }],
	[pgTypeOids.float8Array, { elementOid: pgTypeOids.float8, delimiter: "," }],
	[
		pgTypeOids.polygonArray,
		{ elementOid: pgTypeOids.polygon, delimiter: "," },
	],
	[pgTypeOids.oidArray, { elementOid: pgTypeOids.oid, delimiter: "," }],
	[
		pgTypeOids.macaddrArray,
		{ elementOid: pgTypeOids.macaddr, delimiter: "," },
	],
	[pgTypeOids.inetArray, { elementOid: pgTypeOids.inet, delimiter: "," }],
	[pgTypeOids.bpcharArray, { elementOid: pgTypeOids.bpchar, delimiter: "," }],
	[
		pgTypeOids.varcharArray,
		{ elementOid: pgTypeOids.varchar, delimiter: "," },
	],
	[pgTypeOids.dateArray, { elementOid: pgTypeOids.date, delimiter: "," }],
	[pgTypeOids.timeArray, { elementOid: pgTypeOids.time, delimiter: "," }],
	[
		pgTypeOids.timestampArray,
		{ elementOid: pgTypeOids.timestamp, delimiter: "," },
	],
	[
		pgTypeOids.timestamptzArray,
		{ elementOid: pgTypeOids.timestamptz, delimiter: "," },
	],
	[
		pgTypeOids.intervalArray,
		{ elementOid: pgTypeOids.interval, delimiter: "," },
	],
	[
		pgTypeOids.numericArray,
		{ elementOid: pgTypeOids.numeric, delimiter: "," },
	],
	[pgTypeOids.timetzArray, { elementOid: pgTypeOids.timetz, delimiter: "," }],
	[pgTypeOids.bitArray, { elementOid: pgTypeOids.bit, delimiter: "," }],
	[pgTypeOids.varbitArray, { elementOid: pgTypeOids.varbit, delimiter: "," }],
	[pgTypeOids.uuidArray, { elementOid: pgTypeOids.uuid, delimiter: "," }],
	[pgTypeOids.pgLsnArray, { elementOid: pgTypeOids.pgLsn, delimiter: "," }],
	[pgTypeOids.jsonbArray, { elementOid: pgTypeOids.jsonb, delimiter: "," }],
	[pgTypeOids.lineArray, { elementOid: pgTypeOids.line, delimiter: "," }],
	[pgTypeOids.cidrArray, { elementOid: pgTypeOids.cidr, delimiter: "," }],
	[pgTypeOids.circleArray, { elementOid: pgTypeOids.circle, delimiter: "," }],
	[
		pgTypeOids.macaddr8Array,
		{ elementOid: pgTypeOids.macaddr8, delimiter: "," },
	],
	[pgTypeOids.moneyArray, { elementOid: pgTypeOids.money, delimiter: "," }],
	[pgTypeOids.xmlArray, { elementOid: pgTypeOids.xml, delimiter: "," }],
	[
		pgTypeOids.cstringArray,
		{ elementOid: pgTypeOids.cstring, delimiter: "," },
	],
];

export const postgresArrayTypes = new Map(arrayTypeEntries);
