/**
 * Generates `src/client/raw.gen.ts`: the public raw surface, where every generated
 * operation is wrapped with {@link wrapRaw} so it speaks the ergonomic result contract
 * ({@link NeonResult} / bare-on-`throwOnError`, typed `NeonError`).
 *
 * Run automatically after `openapi-ts` (see the `generate` package script). Keeping this a
 * generated artifact (rather than hand-authored) means the raw surface can never silently
 * fall behind the generated client — `raw-wrap.test.ts` additionally fails if it does.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const sdkGenPath = resolve(here, "../src/client/sdk.gen.ts");
const outPath = resolve(here, "../src/client/raw.gen.ts");

const source = readFileSync(sdkGenPath, "utf8");
const names = [...source.matchAll(/^export const (\w+) = </gm)]
	.map((m) => m[1])
	.sort((a, b) => a.localeCompare(b));

if (names.length === 0) {
	throw new Error("generate-raw: no exported operations found in sdk.gen.ts");
}

const imports = names.map((n) => `\t${n} as _${n},`).join("\n");
const exports = names
	.map((n) => `export const ${n} = wrapRaw(_${n});`)
	.join("\n");

const out = `// This file is auto-generated by scripts/generate-raw.mjs. Do not edit.
// It wraps every generated operation from ./sdk.gen.ts with the ergonomic result contract.

import { wrapRaw } from "../neon/raw-wrap.js";
import {
${imports}
} from "./sdk.gen.js";

${exports}
`;

writeFileSync(outPath, out);
console.log(`generate-raw: wrote ${names.length} wrapped operations to ${outPath}`);
