// Generated by packages/live/scripts/generate-protocol.mjs. Do not edit.
// Source schema SHA-256: 3ee9ce39cdb894fc59864b842d0ddb1c54a4bd040d50d63502154985cb30ac32

export type NeonLiveProtocolV1 = ClientMessage | ServerMessage;
export type ClientMessage =
  | {
      type: "subscribe";
      request_id: U64;
      authorization: string;
    }
  | {
      type: "renew";
      live_id: U64;
      authorization: string;
    }
  | {
      type: "unsubscribe";
      live_id: U64;
    }
  | {
      type: "ping" | "pong";
      token: HeartbeatToken;
    };
export type U64 = string;
export type HeartbeatToken = string;
export type ServerMessage =
  | {
      type: "ready";
    }
  | {
      type: "subscribed";
      request_id: U64;
      live_id: U64;
      epoch: U64;
      first_sequence: U64;
      columns: Column[];
    }
  | {
      type: "subscribe_rejected";
      request_id: U64;
      code:
        | "authorization_failed"
        | "authorization_expired"
        | "backend_unavailable"
        | "upstream_rejected"
        | "resource_exhausted"
        | "service_unavailable";
      message: string;
    }
  | {
      type: "renewed" | "unsubscribed";
      live_id: U64;
    }
  | {
      type: "snapshot_start";
      live_id: U64;
      epoch: U64;
      snapshot_attempt: U64;
      mvcc: Mvcc;
    }
  | {
      type: "snapshot_chunk";
      live_id: U64;
      epoch: U64;
      snapshot_attempt: U64;
      index: U32;
      rows: Row[];
    }
  | {
      type: "snapshot_end";
      live_id: U64;
      epoch: U64;
      snapshot_attempt: U64;
      chunk_count: U32;
    }
  | {
      type: "open";
      publication_id: PublicationId;
    }
  | {
      type: "keyed_results";
      publication_id: PublicationId;
      index: U32;
      txids: U64[];
      targets: ChangeTarget[];
      changes: Change[];
    }
  | {
      type: "reset_required";
      publication_id: PublicationId;
      index: U32;
      targets: ResetTarget[];
    }
  | {
      type: "commit";
      publication_id: PublicationId;
      body_count: U32;
      frontier: {
        lsn: string;
      };
    }
  | {
      type: "subscription_error";
      live_id: U64;
      code:
        | "authorization_expired"
        | "renewal_failed"
        | "key_retired"
        | "upstream_cancelled"
        | "snapshot_failed"
        | "protocol_error";
      message: string;
    }
  | {
      type: "connection_error";
      code:
        | "protocol_error"
        | "invalid_payload"
        | "message_too_large"
        | "resource_exhausted"
        | "slow_consumer"
        | "heartbeat_timeout"
        | "backend_session_lost"
        | "backend_protocol_error"
        | "fence_failed"
        | "internal_error";
      message: string;
    }
  | {
      type: "ping" | "pong";
      token: HeartbeatToken;
    };
export type I32 = number;
export type U32 = number;
export type RowKey = string;
export type Cell = null | string | Base64Cell;
export type PublicationId = string;
export type Change =
  | {
      op: "upsert";
      row_key: RowKey;
      values: Cell[];
    }
  | {
      op: "remove";
      row_key: RowKey;
    };

export interface Column {
  name: string;
  type_oid: number;
  typmod: I32;
  codec: "pg_text" | "bytes";
}
export interface Mvcc {
  xmin: U64;
  xmax: U64;
  xip: U64[];
}
export interface Row {
  row_key: RowKey;
  values: Cell[];
}
export interface Base64Cell {
  base64: string;
}
export interface ChangeTarget {
  live_id: U64;
  epoch: U64;
  sequence: U64;
}
export interface ResetTarget {
  live_id: U64;
  epoch: U64;
  first_sequence: U64;
}
